apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jfmgd
  template:
    metadata:
      labels:
        app: jfmgd 
    spec:
      containers:
      - image: okteto.dev/jfmgd:latest
        name: jfmgd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e17c9810-a7b4-4316-ad64-9e5432caf963"
        - name: Vless_Path
          value: "/vlng135"
        - name: Vmess_UUID
          value: "e17c9810-a7b4-4316-ad64-9e5432caf963"
        - name: Vmess_Path
          value: "/vmcjuj135"
        - name: Share_Path
          value: "/v2link"
